spring:
  application:
    name: ms-video
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 1000ms
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:videos}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  region: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY:test_access_key}
    secret-key: ${AWS_SECRET_KEY:test_secret_access_key}
  s3:
    bucket-name: videos-sent
    endpoint: ${AWS_ENDPOINT:https://s3.localhost.localstack.cloud:4566}
