spring:
  application:
    name: ms-video
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:videos}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  region: ${AWS_REGION:us-east-1}
  sqs:
    queue: ${AWS_SQS_ENDPOINT:https://localhost.localstack.cloud:4566/000000000000}
  credentials:
    access-key: ${AWS_ACCESS_KEY:test_access_key}
    secret-key: ${AWS_SECRET_KEY:test_secret_access_key}
  s3:
    bucket-name: videos-sent
    endpoint: ${AWS_S3_ENDPOINT:https://s3.localhost.localstack.cloud:4566}

rabbitmq:
  send:
    queue:
      name: ${SEND_QUEUE:process-video}
  update:
    queue:
      name: ${UPDATE_QUEUE:update-video-status}