services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videos
    ports:
      - "5432:5432"
    networks:
      - soatnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"     # porta para comunicação AMQP
      - "15672:15672"   # porta da interface web de gerenciamento
    networks:
      - soatnet

  ms-video:
    container_name: ms-video
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - soatnet

volumes:
  postgres_data:

networks:
  soatnet:
    driver: bridge
